#!/usr/bin/env bash
# Configure my Nginx server so that /redirect_me is redirecting to another page.
apt-get -y update
apt-get -y install nginx
sudo echo 'Holberton School' | sudo tee /var/www/html/index.nginx-debian.html
service nginx start
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
